# args for celeba hq

default_args = {
 'batch_size': 8,
 'beta1': 0.0,
 'beta2': 0.99,
 'checkpoint_dir': 'expr/checkpoints',
 'ds_iter': 100000,
 'eval_dir': 'expr/eval',
 'eval_every': 50000,
 'f_lr': 1e-06,
 'hidden_dim': 512,
 'img_size': 256,
 'inp_dir': 'assets/representative/custom/female',
 'lambda_cyc': 1,
 'lambda_ds': 1,
 'lambda_reg': 1,
 'lambda_sty': 1,
 'latent_dim': 16,
 'lm_path': 'expr/checkpoints/celeba_lm_mean.npz',
 'lr': 0.0001,
 'mode': 'train',
 'num_domains': 2,
 'num_outs_per_domain': 10,
 'num_workers': 4,
 'out_dir': 'assets/representative/celeba_hq/src/female',
 'print_every': 10,
 'randcrop_prob': 0.5,
 'ref_dir': 'assets/representative/celeba_hq/ref',
 'result_dir': 'expr/results',
 'resume_iter': 0,
 'sample_dir': 'expr/samples',
 'sample_every': 5000,
 'save_every': 10000,
 'seed': 777,
 'src_dir': 'assets/representative/celeba_hq/src',
 'style_dim': 64,
 'total_iters': 100000,
 'train_img_dir': 'data/celeba_hq/train',
 'val_batch_size': 32,
 'val_img_dir': 'data/celeba_hq/val',
 'w_hpf': 1,
 'weight_decay': 0.0001,
 'wing_path': 'expr/checkpoints/wing.ckpt',
 'shit': 0
}


args_teacher = {
    'model_type': 'teacher',
    'mode': 'eval',
    'num_domains': 2,
    'w_hpf': 1,
    'resume_iter': 100000,
    'train_img_dir': 'data/celeba_hq/train',
    'val_img_dir': 'data/celeba_hq/val',
    'checkpoint_dir': 'expr/checkpoints/celeba_hq',
    'eval_dir': 'expr/eval/celeba_hq'
}

args_student = {
    'model_type': 'student',
    'mode': 'train',
    'resume_iter': 0,
    'num_domains': 2,
    'w_hpf': 1,
    'lambda_reg': 1,
    'lambda_sty': 1,
    'lambda_ds': 1,
    'lambda_cyc': 1,
    'lambda_mse': 1,
    'lambda_perc': 10,
    'lambda_gka': 10,
    'lambda_wavelet': 0,
    'train_img_dir': 'data/celeba_hq/train',
    'val_img_dir': 'data/celeba_hq/val',
    'checkpoint_dir': 'expr/checkpoints/celeba_hq_student/exp_distill',
    'eval_dir': 'expr/eval/celeba_hq_student/exp_cuda0',
    'sample_every': 4000,
    'eval_every': 10000,
    'save_every': 10000,
}